require('General.Sets')
require('General.Vars')
require('General.Mappings')

require('impatient')
require('Plugins')

require('PluginConfig.CatppuccinConfig')
require('PluginConfig.Lsp')
require('PluginConfig.CmpConfig')
require('PluginConfig.Treesitter')
require('PluginConfig.CommenterConfig')
require('PluginConfig.TelescopeConfig')
require('PluginConfig.ColorizerConfig')
require('PluginConfig.NvimTreeConfig')
require('PluginConfig.GitsignsConfig')
require('PluginConfig.FelineConfig')
require('PluginConfig.NeorgConfig')

require('Colors')
