require('core.sets')
require('core.vars')
require('core.mappings')

require('plugins')

require('plugins_config.mason')
require('plugins_config.lsp')
require('plugins_config.null_ls')
require('plugins_config.cmp')
require('plugins_config.snippet')
require('plugins_config.treesitter')
require('plugins_config.comment')
require('plugins_config.telescope')
require('plugins_config.colorizer')
require('plugins_config.gitsigns')
require('plugins_config.feline')
require('plugins_config.dressing')
require('plugins_config.oil')
require('plugins_config.noice')
require('plugins_config.notify')
require('plugins_config.dap')
require('plugins_config.guess_indent')
require('plugins_config.fidget')

require('colors')
